### ISSUE TITLE
Memory leak in ctor of template dds::protocol_api::SHandlerHlpBaseFunc

### ISSUE THREAD

**Issue by dennisklein** [FairRootGroup/DDS#260]
**Affects**: `2.5-47-ga7b10b1`
**OS**: Linux Fedora `30`, GCC `9.1.1`
**Boost**: `1.69.0`

On one of our unit tests:
```
SUMMARY: AddressSanitizer: 10864 byte(s) leaked in 296 allocation(s).
```

All of them seem to be similar, e.g.:

```
Indirect leak of 1 byte(s) in 1 object(s) allocated from:
    #0 0x7f3a871ff9d7 in operator new(unsigned long) (/lib64/libasan.so.5+0x10f9d7)
    #1 0x7f3a86648ae5 in boost::signals2::detail::signal_impl<void (dds::protocol_api::SSenderInfo const&, std::shared_ptr<dds::protocol_api::SEmptyCmd>), boost::signals2::optional_last_value<void>, int, std::less<int>, boost::function<void (dds::protocol_api::SSenderInfo const&, std::shared_ptr<dds::protocol_api::SEmptyCmd>)>, boost::function<void (boost::signals2::connection const&, dds::protocol_api::SSenderInfo const&, std::shared_ptr<dds::protocol_api::SEmptyCmd>)>, boost::signals2::mutex>::invocation_state::invocation_state(boost::signals2::detail::grouped_list<int, std::less<int>, boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (dds::protocol_api::SSenderInfo const&, std::shared_ptr<dds::protocol_api::SEmptyCmd>), boost::function<void (dds::protocol_api::SSenderInfo const&, std::shared_ptr<dds::protocol_api::SEmptyCmd>)> >, boost::signals2::mutex> > > const&, boost::signals2::optional_last_value<void> const&) (/home/dklein/projects/DDS/install/lib/libdds_intercom_lib.so+0x523ae5)
    #2 0x7f3a86638feb in boost::signals2::detail::signal_impl<void (dds::protocol_api::SSenderInfo const&, std::shared_ptr<dds::protocol_api::SEmptyCmd>), boost::signals2::optional_last_value<void>, int, std::less<int>, boost::function<void (dds::protocol_api::SSenderInfo const&, std::shared_ptr<dds::protocol_api::SEmptyCmd>)>, boost::function<void (boost::signals2::connection const&, dds::protocol_api::SSenderInfo const&, std::shared_ptr<dds::protocol_api::SEmptyCmd>)>, boost::signals2::mutex>::signal_impl(boost::signals2::optional_last_value<void> const&, std::less<int> const&) (/home/dklein/projects/DDS/install/lib/libdds_intercom_lib.so+0x513feb)
    #3 0x7f3a8662b87d in boost::signals2::signal<void (dds::protocol_api::SSenderInfo const&, std::shared_ptr<dds::protocol_api::SEmptyCmd>), boost::signals2::optional_last_value<void>, int, std::less<int>, boost::function<void (dds::protocol_api::SSenderInfo const&, std::shared_ptr<dds::protocol_api::SEmptyCmd>)>, boost::function<void (boost::signals2::connection const&, dds::protocol_api::SSenderInfo const&, std::shared_ptr<dds::protocol_api::SEmptyCmd>)>, boost::signals2::mutex>::signal(boost::signals2::optional_last_value<void> const&, std::less<int> const&) (/home/dklein/projects/DDS/install/lib/libdds_intercom_lib.so+0x50687d)
    #4 0x7f3a8661e190 in dds::protocol_api::SHandlerHlpBaseFunc<boost::signals2::signal<void (dds::protocol_api::SSenderInfo const&, std::shared_ptr<dds::protocol_api::SEmptyCmd>), boost::signals2::optional_last_value<void>, int, std::less<int>, boost::function<void (dds::protocol_api::SSenderInfo const&, std::shared_ptr<dds::protocol_api::SEmptyCmd>)>, boost::function<void (boost::signals2::connection const&, dds::protocol_api::SSenderInfo const&, std::shared_ptr<dds::protocol_api::SEmptyCmd>)>, boost::signals2::mutex> >::SHandlerHlpBaseFunc() (/home/dklein/projects/DDS/install/lib/libdds_intercom_lib.so+0x4f9190)
    #5 0x7f3a866afae4 in void dds::protocol_api::CBaseEventHandlersImpl<dds::protocol_api::ECmdType>::registerHandlerImpl<(dds::protocol_api::ECmdType)7, void, dds::protocol_api::SSenderInfo const&, std::shared_ptr<dds::protocol_api::SEmptyCmd> >(std::function<void (dds::protocol_api::SSenderInfo const&, std::shared_ptr<dds::protocol_api::SEmptyCmd>)>) (/home/dklein/projects/DDS/install/lib/libdds_intercom_lib.so+0x58aae4)
    #6 0x7f3a866ae94f in void dds::protocol_api::CChannelMessageHandlersImpl::registerHandler<(dds::protocol_api::ECmdType)7, dds::protocol_api::CClientChannelImpl<dds::internal_api::CAgentChannel>::CClientChannelImpl(boost::asio::io_context&, dds::protocol_api::EChannelType, unsigned long)::{lambda(dds::protocol_api::SSenderInfo const&, std::shared_ptr<dds::protocol_api::SEmptyCmd>)#1}>(dds::protocol_api::CClientChannelImpl<dds::internal_api::CAgentChannel>::CClientChannelImpl(boost::asio::io_context&, dds::protocol_api::EChannelType, unsigned long)::{lambda(dds::protocol_api::SSenderInfo const&, std::shared_ptr<dds::protocol_api::SEmptyCmd>)#1}, std::enable_if<std::is_same<std::integral_constant<dds::protocol_api::ECmdType, (dds::protocol_api::ECmdType)7>, std::is_same<dds::protocol_api::ECmdType, (dds::protocol_api::ECmdType)7> >::value&&std::is_convertible<dds::protocol_api::CClientChannelImpl<dds::internal_api::CAgentChannel>::CClientChannelImpl(boost::asio::io_context&, dds::protocol_api::EChannelType, unsigned long)::{lambda(dds::protocol_api::SSenderInfo const&, std::shared_ptr<dds::protocol_api::SEmptyCmd>)#1}, std::function<void (dds::protocol_api::SSenderInfo const&, std::shared_ptr<dds::protocol_api::SEmptyCmd>)> >::value, void>::type*) (/home/dklein/projects/DDS/install/lib/libdds_intercom_lib.so+0x58994f)
    #7 0x7f3a866ad5db in dds::protocol_api::CClientChannelImpl<dds::internal_api::CAgentChannel>::CClientChannelImpl(boost::asio::io_context&, dds::protocol_api::EChannelType, unsigned long) (/home/dklein/projects/DDS/install/lib/libdds_intercom_lib.so+0x5885db)
    #8 0x7f3a866a9590 in dds::internal_api::CAgentChannel::CAgentChannel(boost::asio::io_context&, unsigned long) (/home/dklein/projects/DDS/install/lib/libdds_intercom_lib.so+0x584590)
    #9 0x7f3a866074f5 in dds::protocol_api::CBaseChannelImpl<dds::internal_api::CAgentChannel>::makeNew(boost::asio::io_context&, unsigned long) (/home/dklein/projects/DDS/install/lib/libdds_intercom_lib.so+0x4e24f5)
    #10 0x7f3a865e7e9c in dds::internal_api::CIntercomServiceCore::setupChannel(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (/home/dklein/projects/DDS/install/lib/libdds_intercom_lib.so+0x4c2e9c)
    #11 0x7f3a865e6cdc in dds::internal_api::CIntercomServiceCore::start(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (/home/dklein/projects/DDS/install/lib/libdds_intercom_lib.so+0x4c1cdc)
    #12 0x7f3a865b236b in dds::intercom_api::CIntercomService::start(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (/home/dklein/projects/DDS/install/lib/libdds_intercom_lib.so+0x48d36b)
    #13 0x7f3a86c2f861 in dds::tools_api::CSession::subscribe() (/home/dklein/projects/DDS/install/lib/libdds_tools_lib.so+0x25e861)
    #14 0x7f3a86c2ea85 in dds::tools_api::CSession::create() (/home/dklein/projects/DDS/install/lib/libdds_tools_lib.so+0x25da85)
    #15 0x7f3a8704e009 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<fair::mq::sdk::DDSSession::Impl, std::allocator<fair::mq::sdk::DDSSession::Impl>, fair::mq::sdk::DDSEnvironment>(fair::mq::sdk::DDSSession::Impl*&, std::_Sp_alloc_shared_tag<std::allocator<fair::mq::sdk::DDSSession::Impl> >, fair::mq::sdk::DDSEnvironment&&) /home/dklein/projects/FairMQ3/fairmq/sdk/DDSSession.cxx:65
    #16 0x7f3a8704e009 in std::__shared_ptr<fair::mq::sdk::DDSSession::Impl, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<fair::mq::sdk::DDSSession::Impl>, fair::mq::sdk::DDSEnvironment>(std::_Sp_alloc_shared_tag<std::allocator<fair::mq::sdk::DDSSession::Impl> >, fair::mq::sdk::DDSEnvironment&&) /usr/include/c++/9/bits/shared_ptr_base.h:1344
    #17 0x7f3a8704e009 in std::shared_ptr<fair::mq::sdk::DDSSession::Impl>::shared_ptr<std::allocator<fair::mq::sdk::DDSSession::Impl>, fair::mq::sdk::DDSEnvironment>(std::_Sp_alloc_shared_tag<std::allocator<fair::mq::sdk::DDSSession::Impl> >, fair::mq::sdk::DDSEnvironment&&) /usr/include/c++/9/bits/shared_ptr.h:359
    #18 0x7f3a8704e009 in std::shared_ptr<fair::mq::sdk::DDSSession::Impl> std::allocate_shared<fair::mq::sdk::DDSSession::Impl, std::allocator<fair::mq::sdk::DDSSession::Impl>, fair::mq::sdk::DDSEnvironment>(std::allocator<fair::mq::sdk::DDSSession::Impl> const&, fair::mq::sdk::DDSEnvironment&&) /usr/include/c++/9/bits/shared_ptr.h:702
    #19 0x7f3a8704e009 in std::shared_ptr<fair::mq::sdk::DDSSession::Impl> std::make_shared<fair::mq::sdk::DDSSession::Impl, fair::mq::sdk::DDSEnvironment>(fair::mq::sdk::DDSEnvironment&&) /usr/include/c++/9/bits/shared_ptr.h:718
    #20 0x7f3a8704e009 in fair::mq::sdk::DDSSession::DDSSession(fair::mq::sdk::DDSEnvironment) /home/dklein/projects/FairMQ3/fairmq/sdk/DDSSession.cxx:143
    #21 0x4bd13f in fair::mq::test::TopologyFixture::TopologyFixture() /home/dklein/projects/FairMQ3/test/sdk/Fixtures.h:50
    #22 0x4945bc in Topology_AsyncChangeState_Test /home/dklein/projects/FairMQ3/test/sdk/_topology.cxx:48
    #23 0x4945bc in CreateTest /home/dklein/projects/FairMQ3/build/extern/googletest_install/include/gtest/internal/gtest-internal.h:460
    #24 0x5140cc in testing::Test* testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::TestFactoryBase, testing::Test*>(testing::internal::TestFactoryBase*, testing::Test* (testing::internal::TestFactoryBase::*)(), char const*) (/home/dklein/projects/FairMQ3/build/test/testsuite_SDK+0x5140cc)
    #25 0x50daf2 in testing::Test* testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::TestFactoryBase, testing::Test*>(testing::internal::TestFactoryBase*, testing::Test* (testing::internal::TestFactoryBase::*)(), char const*) (/home/dklein/projects/FairMQ3/build/test/testsuite_SDK+0x50daf2)
    #26 0x4eccac in testing::TestInfo::Run() (/home/dklein/projects/FairMQ3/build/test/testsuite_SDK+0x4eccac)
    #27 0x4ed372 in testing::TestSuite::Run() (/home/dklein/projects/FairMQ3/build/test/testsuite_SDK+0x4ed372)
    #28 0x4f8541 in testing::internal::UnitTestImpl::RunAllTests() (/home/dklein/projects/FairMQ3/build/test/testsuite_SDK+0x4f8541)
    #29 0x5151bb in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (/home/dklein/projects/FairMQ3/build/test/testsuite_SDK+0x5151bb)
    #30 0x50e856 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (/home/dklein/projects/FairMQ3/build/test/testsuite_SDK+0x50e856)
    #31 0x4f701b in testing::UnitTest::Run() (/home/dklein/projects/FairMQ3/build/test/testsuite_SDK+0x4f701b)
    #32 0x438704 in RUN_ALL_TESTS() /home/dklein/projects/FairMQ3/build/extern/googletest_install/include/gtest/gtest.h:2472
    #33 0x438704 in main /home/dklein/projects/FairMQ3/build/test/runner.cxx:37
    #34 0x7f3a85718f32 in __libc_start_main (/lib64/libc.so.6+0x23f32)
```

[full_asan_log.txt](https://github.com/FairRootGroup/DDS/files/3566637/full_asan_log.txt) (somehow all log messages are doubled...)

**Comment by AnarManafov** [comment]
@dennisklein , I tried to look into this issue once again. Seems to me a leak in the signal2 lib of boost.
When you have a chance, could you please try it with newer boost (1.74+).

In meantime, I am going to configure and build with "fsanitize" and clang. If noting comes up, I will try gcc.
